apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: python-app
build:
  tagPolicy:
    dateTime: {}
  artifacts:
    - image: fastapi-in-ddd
      docker:
        dockerfile: Dockerfile
  local:
    useDockerCLI: true
    useBuildkit: true
profiles:
  - name: python-app
    manifests:
      rawYaml:
        - deployment/python-app/deployment.yaml
