apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: api-srv
build:
  tagPolicy:
    dateTime: { }
  local:
    useDockerCLI: true
    useBuildkit: true
profiles:
  - name: api-srv
    build:
      artifacts:
        - image: api-srv
          docker:
            dockerfile: api-srv/Dockerfile
    manifests:
      rawYaml:
        - deploy/api-srv/deployment.yaml
  - name: checkout-srv
    build:
      artifacts:
        - image: checkout-srv
          docker:
            dockerfile: checkout-srv/Dockerfile
    manifests:
      rawYaml:
        - deploy/checkout-srv/deployment.yaml
