apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipeline
spec:
  httpPipeline:
    handlers:
    - type: middleware.http.uppercase
      name: uppercase
  appHttpPipeline: # for outgoing http calls
    handlers:
      - name: uppercase
        type: middleware.http.uppercase
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"