---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "testapp"
        dapr.io/app-port: "8000"
        dapr.io/config: "pipeline"
    spec:
      containers:
      - name: rest-app
        image: fastapi-in-ddd
        ports:
        - name: rest
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
  - name: rest
    port: 8052
    targetPort: 8000
