---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-srv
  labels:
    app: checkout-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-srv
  template:
    metadata:
      labels:
        app: checkout-srv
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "checkout-srv"
        dapr.io/app-port: "8000"
    spec:
      containers:
      - name: checkout-srv
        image: checkout-srv
        ports:
        - name: rest
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-srv
spec:
  type: LoadBalancer
  selector:
    app: checkout-srv
  ports:
  - name: rest
    port: 8051
    targetPort: 8000
