---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-srv
  labels:
    app: api-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-srv
  template:
    metadata:
      labels:
        app: api-srv
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "api-srv"
        dapr.io/app-port: "8000"
    spec:
      containers:
        - name: api-srv
          image: api-srv
          ports:
            - name: rest
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  type: LoadBalancer
  selector:
    app: api-srv
  ports:
    - name: rest
      port: 8051
      targetPort: 8000
